# Generated by Django 4.2.21 on 2025-05-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongThucMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_xuat', models.DateField()),
                ('ten_mon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HangHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hang_hoa', models.CharField(max_length=255, unique=True)),
                ('don_vi_hang_hoa', models.CharField(max_length=50)),
                ('don_vi_nguyen_lieu', models.CharField(max_length=50)),
                ('dinh_luong', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='KyTonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ky', models.CharField(max_length=255)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='XuatMonTheoFabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_xuat', models.DateField()),
                ('nhom_mon', models.CharField(max_length=100)),
                ('loai_mon', models.CharField(max_length=100)),
                ('don_vi_tinh', models.CharField(max_length=50)),
                ('so_luong', models.FloatField()),
                ('ten_mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.congthucmon')),
            ],
        ),
        migrations.CreateModel(
            name='TongHopXuatNguyenLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinh_luong', models.FloatField()),
                ('so_mon_xuat', models.FloatField()),
                ('nguyen_lieu_da_xuat', models.FloatField()),
                ('cong_thuc_mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.congthucmon')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hanghoa')),
            ],
        ),
        migrations.CreateModel(
            name='NhapHangHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhap', models.DateField()),
                ('so_luong', models.FloatField()),
                ('don_vi_hang_hoa', models.CharField(blank=True, max_length=50)),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hanghoa')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietCongThucMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinh_luong', models.FloatField()),
                ('cong_thuc_mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='home.congthucmon')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hanghoa')),
            ],
        ),
        migrations.CreateModel(
            name='TonKhoHangHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_ton', models.DateField()),
                ('so_luong_ton', models.FloatField()),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hanghoa')),
            ],
            options={
                'unique_together': {('hang_hoa', 'ngay_ton')},
            },
        ),
    ]
