# Generated by Django 4.2.21 on 2025-05-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congthucmon',
            name='ngay_xuat',
        ),
    ]
