# Generated by Django 4.2.21 on 2025-05-18 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_congthucmon_ngay_xuat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonghopxuatnguyenlieu',
            name='ngay_xuat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tonghopxuatnguyenlieu',
            name='nguyen_lieu_da_xuat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tonghopxuatnguyenlieu',
            name='so_mon_xuat',
            field=models.FloatField(default=0),
        ),
    ]
