# Generated by Django 4.2.21 on 2025-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_tonkhohanghoa_so_luong_ton_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tonkhohanghoa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tonkhohanghoa',
            name='don_vi_hang_hoa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tonkhohanghoa',
            name='so_luong_ton',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tonkhohanghoa',
            name='ton_cuoi_ngay',
        ),
        migrations.RemoveField(
            model_name='tonkhohanghoa',
            name='ton_dau_ngay',
        ),
    ]
