# Generated by Django 4.2.21 on 2025-05-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tonkhohanghoa_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tonkhohanghoa',
            name='so_luong_ton',
        ),
        migrations.AddField(
            model_name='tonkhohanghoa',
            name='ton_cuoi_ngay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tonkhohanghoa',
            name='ton_dau_ngay',
            field=models.FloatField(default=0),
        ),
    ]
