# Generated by Django 4.2.21 on 2025-05-27 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_tonkhohanghoa_so_luong_ton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TonKhoLeTan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_ton', models.DateField()),
                ('ton_dau_ngay', models.FloatField(default=0.0)),
                ('ton_cuoi_ngay', models.FloatField()),
                ('don_vi_hang_hoa', models.CharField(blank=True, max_length=50)),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hanghoa')),
            ],
            options={
                'verbose_name': 'Tồn Kho Lễ Tân',
                'verbose_name_plural': 'Tồn Kho Lễ Tân',
                'unique_together': {('hang_hoa', 'ngay_ton')},
            },
        ),
    ]
